name: Deploy to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # This enables OIDC token requests
      contents: read

    steps:
      - name: Debug OIDC Token
        run: |
          echo "Request URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "Request Token: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::886436961042:role/GithubActionsRole
          aws-region: us-east-1

      # Step 3: Verify AWS Access
      - name: Verify AWS Access
        run: aws s3 ls


